services:
  postgres:
    image: postgres:16-alpine
    container_name: dusky-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: duskydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d duskydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_db_data:
